name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload Docker Compose to EC2
        uses: appleboy/ssh-action@master
        env:
          EC2_USER: ubuntu
          EC2_HOST: 52.91.98.167
          EC2_KEY: ${{ env.EC2_KEY }}
        with:
          debug: true
          host: 52.91.98.167
          username: ubuntu
          key: ${{ env.EC2_KEY }}

      - name: Deploy Application on EC2
        uses: appleboy/ssh-action@master
        env:
          EC2_USER: ubuntu
          EC2_HOST: 52.91.98.167
          EC2_KEY: ${{ env.EC2_KEY }}
        with:
          host: 52.91.98.167
          username: ubuntu
          key: ${{ env.EC2_KEY }}
          script: |
            cd /home/ubuntu/
            docker-compose -f docker-compose.yml down
            docker-compose -f docker-compose.yml up -d