name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Debug File Locations
      - name: Debug File Locations
        run: |
          echo "Current directory: $(pwd)"
          ls -al

      # Step 3: Upload Docker Compose to EC2
      - name: Upload Docker Compose to EC2
        uses: appleboy/scp-action@master
        with:
          host: 52.91.98.167
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: docker-compose.yml
          target: /home/ubuntu/

      # Step 4: Debug Uploaded Files on EC2
      - name: Check Files on EC2
        uses: appleboy/ssh-action@master
        with:
          host: 52.91.98.167
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            echo "Checking files on EC2:"
            ls -al /home/ubuntu/

      # Step 5: Deploy Application on EC2
      - name: Deploy Application on EC2
        uses: appleboy/ssh-action@master
        with:
          host: 52.91.98.167
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/
            docker-compose down
            docker-compose up -d
